spring.application.name=reservation-system

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Автоматически создавать таблицы при старте
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jpa.open-in-view=false