create table users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    name varchar(255) not null
);

create table rooms (
    id bigint generated by default as identity primary key,
    capacity integer not null,
    name varchar(255) not null
);

create table reservations (
    id bigint generated by default as identity primary key,
    end_date date not null,
    start_date date not null,
    status varchar(255) not null,
    room_id bigint not null references rooms (id),
    user_id bigint not null references users (id)
);